---
title: "ITC pt 3"
author: "Fayre-Ella Ooi"
date: "2025-04-16"
output: pdf_document
---

```{r}

#dataset 
LookUp = read.csv(file = "/Users/fayreooi/Downloads/LookUpUpdate.csv")
LookUp = LookUp[, -c(11,12,13,14,15)]

## clean dataset

# make numbers numerical
LookUp$Customer.Count = as.numeric(gsub(",", "", LookUp$Customer.Count))

# interpreting SAIDI add a column to dataset showing average minutes  
LookUp$Avg.Min.PerCustomer.2023 = LookUp$X2023.SAIDI * 60

# adding CAIDI 
# LookUp$CAIDI.2023 = LookUp$X2023.SAIDI / LookUp$X2023.SAIFI

# dataset
CircuitOutage = read.csv(file = "/Users/fayreooi/Desktop/circuitWRegions.csv")
CircuitOutage$Outage.Duration..min. = as.numeric(gsub(",", "", CircuitOutage$Outage.Duration..min.))

# add information from circuit outage dataset
# we want to add the CMI from 2024

#add number of circuit outages in 2024
LookUp$Number.Outages.2024 = c(3, 4, 6, 4, 7, 3, 6, 3, 10, 2, 9, 3, 9, 1, 2, 1, 7, 2, 10, 1, 7)

## SAIDI for 2024

tapply(CircuitOutage$Outage.Duration..min., CircuitOutage$Circuit.Name, sum)

LookUp$Avg.Outage.Duration.2024 = c(840.333, 518.25, 919, 470.75, 700.1429, 979, 695.333, 
                                    660.333, 759.7, 768.5, 1025, 915.333, 590.6667, 
                                    411, 1341.5, 72, 845.4286, 615.5, 681.1, 975,
                                    713.4286) 

# SAIFI for 2024

tapply(CircuitOutage$Customers.Affected, CircuitOutage$Circuit.Name, mean)

LookUp$Avg.Customers.Affected.2024 = c(846, 2465, 1684, 473 ,747, 818, 628, 930, 1426,
                                       477, 246, 883, 1204, 1962, 1658, 1201, 719, 
                                       497,1413, 243, 1513)

LookUp$SAIFI.2024 = LookUp$Number.Outages.2024 / LookUp$Customer.Count

# add column of how many miles are overhead/underground

LookUp$Overhead.miles = LookUp$Circuit.Miles * (LookUp$X..Overhead/100)
LookUp$Underground.miles = LookUp$Circuit.Miles * (LookUp$X..Underground/100)

# adding cause count to Look Up data

LookUp$UG.Equipment.Failure = c(0,3,4,0,0,0,3,0,0,0,4,1,1,0,1,0,4,1,0,0,2)
LookUp$OH.Equipment.Failure = c(0,0,0,1,2,0,0,1,3,0,0,0,4,0,0,0,0,0,4,1,1)
LookUp$Third.Party = c(1,1,0,1,0,1,2,1,1,0,0,1,1,0,1,0,0,0,1,0,2)
LookUp$Weather = c(1,0,1,2,1,1,0,0,3,0,1,0,1,0,0,0,0,0,1,0,0)
LookUp$Other = c(1,0,1,0,1,0,0,0,1,0,1,0,2,0,0,1,1,1,0,0,1)
LookUp$Operation = c(0,0,0,0,2,0,1,0,1,1,2,0,0,0,0,0,1,0,2,0,0)
LookUp$Animal = c(0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,1,0,1)
LookUp$Vegetation = c(0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,1,0,0)

# make KV into categories
# LookUp$KV = factor(LookUp$KV,
#                      levels = c(4, 12, 16),
#                      labels = c("Four", "Twelve", "Sixteen"))

# add TOTAL outage duration per circuit in 2024

tapply(CircuitOutage$Outage.Duration..min. , CircuitOutage$Circuit.Name, sum)
LookUp$Total.Outage.Duration = c(2521, 2073, 5514, 1883, 4901, 2937, 4172, 1981, 
                                 7597, 1537,9225, 2746, 5316, 411, 2683, 71, 5918,
                                 1231, 6811,975,4994)

LookUp$SAIDI.2024 = LookUp$Total.Outage.Duration / LookUp$Customer.Count

# add average minutes per customer for 2024
LookUp$Avg.Min.PerCustomer.2024 = LookUp$SAIDI.2024 * 60

# KV-miles
LookUp$KV.Miles = LookUp$Circuit.Miles * LookUp$KV

write.csv(LookUp, "ihateitc.csv", row.names = FALSE)

```

```{r}

SAIFI = LookUp[, c("Circuit.Name","X2023.SAIFI", "SAIFI.2024")]
SAIFI

write.csv(SAIFI, "SAIFI.csv")

SAIDI = LookUp[, c("Circuit.Name", "X2023.SAIDI", "SAIDI.2024")]
SAIDI

write.csv(SAIDI, "SAIDI.csv")
  
Customers.Affected = LookUp[, c("Circuit.Name","Avg.Min.PerCustomer.2024", "Avg.Min.PerCustomer.2023")]
Customers.Affected

```

```{r}

library(leaps)

LookUp.Numerical.1 = LookUp[sapply(LookUp, is.numeric)]
LookUp.Numerical.1 = LookUp.Numerical.1[, -c(4,5,6,7,8,9,13,17,18,19,20,21,22,23,24,25)]
LookUp.Numerical.1 = LookUp.Numerical.1[, -c(5)]
LookUp.Numerical.1 = LookUp.Numerical.1[, -c(9)]

## FOR 2024
cor(LookUp.Numerical.1, use = "complete.obs", method = "pearson")

# choosing number of variables
sub_sel = regsubsets(Number.Outages.2024 ~ ., data = LookUp.Numerical.1, nvmax = 8)
sub_res = summary(sub_sel)

summary(sub_sel)
sub_res$rsq

plot(sub_res$adjr2, xlab = "Number of Variables", ylab = "Adjusted R Squared", type = "l")
points(3, sub_res$adjr2[3], col = "darkred", cex = 2, pch = 20)

# predicting

# FORWARD
regfit_fwd = regsubsets(Number.Outages.2024 ~ . , data = LookUp.Numerical.1,
                        nvmax = 7, method = "forward")
summary(regfit_fwd)

# BACKWARD
regfit_bwd = regsubsets(Number.Outages.2024 ~ . , data = LookUp.Numerical.1,
                        nvmax = 7, method = "backward")
summary(regfit_bwd)

# selecting model based on a criteria (BIC)
num_bic_fwd = which.min( summary(regfit_fwd)$bic)
num_bic_bwd = which.min( summary(regfit_bwd)$bic)
num_bic_best = which.min( summary(sub_sel)$bic)

paste("forward stepwise selection:", num_bic_fwd)
paste("forward stepwise selection:", num_bic_bwd)
paste("forward stepwise selection:", num_bic_best)

coef(regfit_fwd, num_bic_fwd)
coef(regfit_bwd, num_bic_bwd)

## saidi, saifi, and underground miles are the most relevant. 

```
```{r}

set.seed(1220)
train = sample(c(TRUE,FALSE), nrow(LookUp.Numerical.1), replace = TRUE)
test = (!train)

regfit_best = regsubsets(Number.Outages.2024 ~ ., data = LookUp.Numerical.1[train, ],
                         nvmax = 8)

test_mat = model.matrix(Number.Outages.2024 ~ ., data = LookUp.Numerical.1[test, ])
head(test_mat)

p = ncol(test_mat) - 1
val_errors = numeric(p)

for (i in 1:p){
  coef_i <- coef(regfit_best, id = i)
  pred <- test_mat[, names(coef_i)] %*% coef_i
  y_test <- LookUp.Numerical.1$Number.Outages.2024[test]
  val_errors[i] <- mean((y_test - pred)^2)
}

val_errors

which.min(val_errors)

coef(regfit_best, 6)
```



